version: "3.7"

services:
  app:
    container_name: vector_packing_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: True
    ports:
      - '8501:8501'

  notebook:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''